application: whosays-140117
version: 1
runtime: python27
threadsafe: true
api_version: 1


handlers:
- url: /tasks/cache_average_game_points
  script: main.app

- url: /crons/send_reminder
  script: main.app

- url: /_ah/spi/.*
  script: whosays_api.APPLICATION
  secure: always


libraries:
- name: endpoints
  version: 1.0

